### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by DarthRaki**

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
Thank you @DarthRaki ! I 👍 🎊

**Comment by Cyb3rWard0g** [comment]
Quick question @DarthRaki , in the "false positives" part. I was wondering if you tested in a bigger environment. just curious. It would be good to know.

**Comment by Cyb3rWard0g** [comment]
Hey @neu5ron , I was wondering if you could provide some additional feedback to this from your own environment or someone you know that can help us test those network rules?. I do not have access to an environment with that telemetry :( . Let me know if it is possible please. thank you!

**Comment by DarthRaki** [comment]
I will test them at work next week.

**Comment by Cyb3rWard0g** [comment]
Thank you @DarthRaki ! I appreciate all the help and contributions :)

**Comment by Cyb3rWard0g** [comment]
This could be used for https://github.com/OTRF/detection-hackathon-apt29/issues/4 right? @DarthRaki

**Comment by DarthRaki** [comment]
> This could be used for #4 right? @DarthRaki

Not if they are using HTTPS, sadly network sensors dont get to see much over TLS/SSL.

**Comment by Cyb3rWard0g** [comment]
Hey @DarthRaki , I hope you are doing well. I will merge this PR. Feel free to update it with another PR whenever you have a chance to test the rule. Thank you in advance!

**Pull request merged**
